### PR TITLE
Feature/element children pitches

### PR DESCRIPTION
**Pull request by JRegimbal**
Replaces larger `vrv::Toolkit::Query` function but also adds `GetElementChildPitches` and `GetElementStaffDef` to toolkit. I don't think either of these can be easily replicated with preexisting functions in verovio.

We need to get the children for neumes from within verovio since the rendered glyphs categorized as NCs are **not** the actual components for some groupings (ex porrectus).

Clef information is stored in the StaffDef along with plenty of other info, so `GetElementStaffDef` should be useful in other contexts.

@lpugin do you have any comments?

### CODE REVIEW

**Comment by lpugin** [comment]
I don't think you need this. You can easily access each `<nc>` children one by one and call `getElementAttr` for the `<nc>`.  Any reason why this would not work?

**Comment by JRegimbal** [comment]
The way the `<nc>` children are rendered doesn't always match how they are in the MEI. For example we might need to add a connecting line between two punctums and that line will be rendered as a separate child in the SVG, while for the purpose of assigning a grouping to a neume it shouldn't be counted.

**Comment by lpugin** [comment]
This remains unclear for me. Could you provide some examples of the MEI and of corresponding desired output?

**Comment by JRegimbal** [comment]
Okay. We could have a clivis in MEI like this:
```xml
<neume>
    <nc oct="3" pname="g"/>
    <nc intm="d" oct="3" pname="e"/>
</neume>
```
The way a clivis is rendered is with two punctums and a line connecting them. However in the SVG this results in 3 separate glyphs (the puntums and the line) all categorized as being NCs. So if we get the children of the clivis neume that way, we end up with three neume components rather than two and the categorization done on our end outside of verovio fails since the contour is different.

This happens with some other neume groupings too. We also may not use the same number of glyphs to render the same type of neume if the neume component pitches are different. Keeping with the clivis example, if the second neume component is much lower than the first then the line won't be rendered since a sufficiently large connecting line isn't present in SMuFL.

So to get around this we're getting the information on the children directly from verovio. I didn't see an existing function in the toolkit that would allow this, so I wrote `GetElementChildPitches`.

**Comment by lpugin** [comment]
OK. Could you show the corresponding SVG (code and rendering)?

There is something not consistent in the way you structure the SVG. There should be only two `<g class="nc">` children of the `<g class="neume">`. The line should be direct child of `<g class="neume">` or child of the appropriate `<g class="nc">`

**Comment by JRegimbal** [comment]
Here's the relevant snippet of the SVG along with the file itself (as a PNG since github won't let me upload the file). The snippet is of the second neume in the file.
Rendering
```xml
<g class="neume" id="neume-0000002072152309">
        <g class="nc" id="nc-0000000921553964">
                <use xlink:href="#E990" x="1133" y="1269" height="720px" width="720px" />
        </g>
        <g class="nc" id="nc-0000000905410784">
                <use xlink:href="#E9BE" x="1241" y="1449" height="720px" width="720px" />
        </g>
        <g class="nc" id="nc-0000000905410784">
                <use xlink:href="#E990" x="1241" y="1449" height="720px" width="720px" />
        </g>
</g>
```

**Comment by lpugin** [comment]
It seems that is should look like:
```
<g class="neume" id="neume-0000002072152309">
        <g class="nc" id="nc-0000000921553964">
                <use xlink:href="#E990" x="1133" y="1269" height="720px" width="720px" />
                <use xlink:href="#E9BE" x="1241" y="1449" height="720px" width="720px" />
        </g>
        <g class="nc" id="nc-0000000905410784">
                <use xlink:href="#E990" x="1241" y="1449" height="720px" width="720px" />
        </g>
</g>
```

**Comment by JRegimbal** [comment]
Okay we'll try to produce the SVG like that.

**Comment by lpugin** [comment]
This relates to another issue that I mentioned to @ATranimal , namely that all `Nc` should be drawn by a call to `DrawChildrenElements`. You should change it to it. Then you can store in the parent Neume some drawing members. For example, the last Nc and it last (or right?) x position. In DrawNc, then just look for the parent and you should have access to all you need.

**Pull request closed without merging**
